### ISSUE TITLE
update

### ISSUE THREAD

**Issue by shgtjgh** [jeroenpeters1986/MMM-ROVA-trashcalendar#1]
Hi Jeroen,
the module isn't fetching the data anymore.
Have you/could you look into it?
thanks

**Comment by jeroenpeters1986** [comment]
Hey @shgtjgh 
I see, I will have a look at it

**Comment by jeroenpeters1986** [comment]
Hi @shgtjgh I made a change on the remote end. ROVA changed their API. Could you please reload/restart the MagicMirror and let me know if it works?

**Comment by shgtjgh** [comment]
did it.
this is what is says: 
![IMG_3069](https://user-images.githubusercontent.com/80210548/123795970-e28d8280-d8e4-11eb-923b-34a29b2d0a86.jpg)

**Comment by jeroenpeters1986** [comment]
Thanks! Then I'll have to start my own MagicMirror and fix the module as a whole. I think this will work, but this might take a few days

**Comment by shgtjgh** [comment]
Oke!
No worries.
got the paperversion still ;-)
give me notice if it’s done please.
thanks

**Comment by jeroenpeters1986** [comment]
Will do!

**Comment by SkyFocusNL** [comment]
Hi, same problem here, mine lists "Woensdag: Undefined" 5 times. I've looked into the scripts that are used and when calling the API "https://www.jeroenpeters.com/projecten/magicmirror/rova_api.php?z=8014LE&h=7" ... the result is ok.

_PS: Would it be possible to host your api script on my own (internal) server. I don't like to be dependent on other servers like that. When your server is down the ROVA app will not work ..._

**Comment by jeroenpeters1986** [comment]
Hey @SkyFocusNL 
The problem is they changed the output, so I also need to change the module now. 
Before their new API (which is REST without a session), you had to build a session, input the Housenr and Zipcode in a cookie before you could check the new collection-dates. That is why it working on my server, because I had a PHP script there to do the hard work. 
Now ROVA has a new API which doesnt need cookies or a session, I will use that directly, I also like that better ;-)

**Comment by jeroenpeters1986** [comment]
Hi @shgtjgh  and @SkyFocusNL ,

My own magicmirror is having troubles starting up, but I did update the modules. Is one of you (or both) available to test the new version?

**Comment by SkyFocusNL** [comment]
Yup, it is working again. 👍🏼 Thank you very much !

![A6D4D45D-86A5-4E61-B35A-460575066952](https://user-images.githubusercontent.com/11363725/124375644-95722d80-dca3-11eb-8691-2d8f3a19a3f1.jpeg)

Maybe you can explain one small issue howto fix. The trashcan icons are on top of the text (see photo), is it possible somehow to use some styling to place them a little bit to the right  ?

**Comment by shgtjgh** [comment]
A little change in the css

Verstuurd vanaf mijn iPhone

**Comment by jeroenpeters1986** [comment]
Glad to hear it's working again! 
@SkyFocusNL if you are familiair with CSS you could do this I think. In my setup ([as you can see in the screenshot](https://raw.githubusercontent.com/jeroenpeters1986/MMM-ROVA-trashcalendar/master/MMM-ROVA-trashcalendar.png)) it works great, but you can tweak your own version.

If you look at https://github.com/jeroenpeters1986/MMM-ROVA-trashcalendar/blob/master/MMM-ROVA-trashcalendar.css you can see what the current styles are, you can edit them manually on your installation, or override them in a custom.css file for MagicMirror :-)
