### ISSUE TITLE
Node modules not loaded into the folder (Request module needed)

### ISSUE THREAD

**Issue by gertperdZA** [jeroenpeters1986/MMM-ROVA-trashcalendar#2]
Node modules are not being uploaded into the directory after npm install. The module doesn't load as the Request module is missing.

**Comment by jeroenpeters1986** [comment]
I have closed this issue as I think you may have encountered another error for the api error, am I right? or does it still need fixing?

**Comment by gertperdZA** [comment]
You can close it maybe just mention that the ROVA will only work in certain
areas in the Netherlands. Thats the reason why it didn’t work for me.

**Comment by jeroenpeters1986** [comment]
Thats a good addition, for me it was a sure thing but not everyone knows that the ROVA is, and where they operate. 
This module will only work in these areas: https://www.rova.nl/over-ons#gemeenten
