### ISSUE TITLE
More API's for this modules?

### ISSUE THREAD

**Issue by gertperdZA** [jeroenpeters1986/MMM-ROVA-trashcalendar#3]
API is not working anymore. Suggestion would be to have a look at https://api.mijnafvalwijzer.nl/ unless you know the latest API for Rova

**Comment by jeroenpeters1986** [comment]
@gertperdZA are you sure? Here, https://[rova.nl/api/waste-calendar/upcoming?postalcode=8012AR&houseNumber=90&addition=&take=3](https://rova.nl/api/waste-calendar/upcoming?postalcode=8012AR&houseNumber=90&addition=&take=3) seems to be working great. I don't have the module running myself anymore as my MagicMirror is out of use

**Comment by gertperdZA** [comment]
This was the orginal from your code.
https://www.rova.nl/api/waste-calendar/upcoming?postalcode=' +
payload.config.zipCode + '&houseNumber=' + payload.config.houseNr +
'&addition=' + payload.config.houseNrAddition + '&take=3

But your links seems to work without the ‘www’, but it is not working for
my address in Utrecht. Do you know if the Rova service only works for
certain areas in the Netherlands? Postal code 3607NR doesn’t seem to work
with the api.

**Comment by jeroenpeters1986** [comment]
I checked it and at https://rova.nl/over-ons#gemeenten I see that they do not collect trash in Utrecht. They do in Amersfoort, but mainly around the broad Zwolle area. My ROVA module therefore is only for this area

**Comment by gertperdZA** [comment]
That explains it! thank you for checking. Any other api's you know of that I can use instead? I saw there is a small hack with AfvalWijzer, the API is not as clean as you do need to do some array cleanup.

**Comment by jeroenpeters1986** [comment]
I don’t know really actually, this plugin was made specifically for ROVA so I didn’t look any further to be honest.Op 1 mrt 2024 om 10:10 heeft gertperdZA ***@***.***> het volgende geschreven:﻿
That explains it! thank you for checking. Any other api's you know of that I can use instead? I saw there is a small hack with AfvalWijzer, the API is not as clean as you do need to do some array cleanup.

**Comment by gertperdZA** [comment]
I have created a module which now uses the AfvalWijzer api. I have used some of your code , I hope you don't mind. Let me know. My plan is to also to share my module with the community.

**Comment by jeroenpeters1986** [comment]
Hey @gertperdZA nice work! Ofcourse that is OK, the software is open source and if you can use and modify it that way I am pleased that it have helped you!

**Comment by jeroenpeters1986** [comment]
I checked out the code and it seems nice @gertperdZA  :-) Can I close this issue?

**Comment by gertperdZA** [comment]
Yes sure thing 😊
